package:
    name: hdfeos2
    version: 2.19.1

source:
    fn: HDF-EOS2.19v1.00.tar.Z
    url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z
    md5: b8648484fc78a2db7073dd603f3fb251

build:
    number: 5
    skip: True  # [win]

requirements:
    build:
        - hdf4
        - zlib 1.2.*
        - jpeg 9.*
    run:
        - hdf4
        - zlib 1.2.*
        - jpeg 9.*

test:
    commands:
        - test -f ${PREFIX}/lib/libGctp.a  # [unix]
        - test -f ${PREFIX}/lib/libhdfeos.a  # [unix]
        - conda inspect linkages -n _test hdfeos2  # [linux]

about:
    home: http://hdfeos.org/index.php
    license: BSD
    summary: Earth Observing System HDF

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
