# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pFM4XeoLRKHijTm9yJQxvGq1gOwaawI75ZaR/y99mCjq+uePWhH4poYxxVNnKuukBOghIh2Y3Pz6II+yK8cy1xok6pVU3yPpAc1oNAw65vKY6+F0qN+mdXszVXECNcYsztuqCiBZSpw1SUv3xMTR37fL13/RxvCJv2R+G+FUWMSiKuWRefiZqhAkSsybklwXyYIPHPXYBBe7qo/2J+rVEamB/YPXPKYhxXMNegqDmD3Z00BWPqOsWZAqLa0yQCJZSB9VwYS5aVqvS42ABFbz+xKObyH2aIAzV1WBphhWONQvuKS0mKxB5ScEot47kNyU5CKQw7hDNJT3UOg+IIOa15aY6znnfcTA9OrLHCndeQfBZfTjztKUv68xV9OAISSp/uwONZMqxeBfsRcJDBsSDAAiVWAT7d0e7LkI/ivgjjlKLLBIuf4GwIF4tD8y4gRM7y66pnPIzslJJ94j23dHfCNP1VSokPT0pQfDoqRSC+yYel4hiXOQ4wNyeWTeIptr4DInCjipitt7ldC+xJdPIu2Itv1sAHskr1mIMh0QPmpwZ3VIEVHWfpqfXUy8l2cYdmjUziz4f12ddAPEGb04cdiJApxrZPwRnUbBg7v85FoKRy6dWRXmTNNFwnKpYmzVKKea+DgOdBHSnzgN1zxq26yV7xPadLH1RWhQiaswqPc="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
